---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

# ---
# # Backstage User Entity
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: guest
#   title: Guest User
# spec:
#   profile:
#     displayName: Anurag pachauri
#     email: anuragpachauri8@gmail.com
#   memberOf: [guests]

# ---
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: ninad-desai
#   title: Ninad Desai
# spec:
#   profile:
#     displayName: Ninad Desai
#     email: Ninad.desai73@gmail.com
#   memberOf: [guests]
