private_ip     = true
swap_size      = "${{ values.swap_size }}"
linode_token   = "${{ values.linode_token }}"
vm_label       = "${{ values.vm_label }}"
region         = "${{ values.region }}"
instance_type  = "${{ values.instance_type }}"
admin_password = "${{ values.admin_password }}"
ssh_key        = "${{ values.ssh_key }}"
tagvalue       = "${{ values.tagvalue }}"
